name: b7c_clean_architecture
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: 0.13.4
  platform_device_id: ^1.0.1
  shared_preferences: ^2.0.13
  provider: ^6.0.1
  flutter_dotenv: ^5.0.2
  google_fonts: ^3.0.1
  carousel_slider: ^4.2.1
  google_maps_flutter: ^2.2.3
  location: ^4.4.0
  flutter_image_compress: ^1.1.3
  path_provider: ^2.0.4
  camera: ^0.9.2+2
  intl: ^0.17.0
  image_picker: ^0.8.6+3
  form_field_validator: ^1.1.0
  im_stepper: ^1.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env.dev
    - .env.prod
    - .env.uat

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/Ubuntu/Ubuntu-Bold.ttf
        - asset: assets/Ubuntu/Ubuntu-BoldItalic.ttf
          style: italic
        - asset: assets/Ubuntu/Ubuntu-Italic.ttf
          weight: 700
        - asset: assets/Ubuntu/Ubuntu-Light.ttf
          weight: 700
          style: italic
        - asset: assets/Ubuntu/Ubuntu-LightItalic.ttf
          weight: 300
        - asset: assets/Ubuntu/Ubuntu-Medium.ttf
          weight: 300
          style: italic
        - asset: assets/Ubuntu/Ubuntu-MediumItalic.ttf
          weight: 500
        - asset: assets/Ubuntu/Ubuntu-Regular.ttf
          weight: 500
          style: italic
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
